name: Amazon Inspector Image Scan
on:
  workflow_call:
    inputs:
      docker-context:
        required: false
        type: string
        default: '.'
      docker-file:
        required: false
        type: string
        default: 'Dockerfile'
      docker-image-name:
        required: false
        type: string
        default: ${{ github.repository }}
      inspector-sbomgen-path:
        required: false
        type: string
        default: "./inspector-sbomgen"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-context }}
          push: true
          tags: localhost:5000/${{ inputs.docker-image-name }}:latest
      - name: Check cURL version
        run: curl -V
      - name: Setup Inspector Sbomgen
        run: >
          mkdir -p "${{ inputs.inspector-sbomgen-path }}"
          && curl -o "https://amazon-inspector-sbomgen.s3.amazonaws.com/latest/linux/amd64/inspector-sbomgen.zip"
          && unzip -qq -j inspector-sbomgen.zip -d "${{ inputs.inspector-sbomgen-path }}"
          && chmod +x "${{ inputs.inspector-sbomgen-path }}/inspector-sbomgen"
          && echo "${{ inputs.inspector-sbomgen-path }}/inspector-sbomgen" >> $GITHUB_PATH
      - name: Test Inspector Sbomgen
        run: inspector-sbomgen --version