name: Amazon Inspector Image Scan
on:
  workflow_call:
    inputs:
      docker-context:
        required: false
        type: string
        default: '.'
      docker-file:
        required: false
        type: string
        default: 'Dockerfile'
      docker-image-name:
        required: false
        type: string
        default: ${{ github.repository }}
      amazon-inspector-scan-region:
        required: true
        type: string
      amazon-inspector-scan-endpoint:
        required: true
        type: string
      amazon-inspector-scan-assume-role:
        required: true
        type: string
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      inspector_sbomgen_output_path: "${{ github.workspace }}/container-sbom.json"
      inspector_scan_endpoint: "${{ inputs.amazon-inspector-scan-endpoint }}"
      inspector_scan_region: "${{ inputs.amazon-inspector-scan-region }}"
      inspector_vulnerability_report_path: "${{ github.workspace }}/vulnerability-report.json"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-context }}
          push: false
          tags: ${{ inputs.docker-image-name }}:latest
      - name: Setup Amazon Inspector SBOM Generator
        uses: build-failure/setup-inspector-sbomgen@v1
      - name: Scan Local Image
        run: "$inspector_sbomgen container --image ${{ inputs.docker-image-name }}:latest -o $inspector_sbomgen_output_path"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.amazon-inspector-scan-region }}
          role-to-assume:  ${{ inputs.amazon-inspector-scan-assume-role }}
          role-duration-seconds: 1200
          mask-aws-account-id: true
      - id: scan_sbom
        name: Retrieve Vulnerability Report
        run: >
          aws inspector-scan scan-sbom
          --sbom file://"$inspector_sbomgen_output_path"
          --endpoint "$inspector_scan_endpoint"
          --region "$inspector_scan_region" > $inspector_vulnerability_report_path
      - name: Validate Vulnerability Threshold
        uses: build-failure/vulnerability-threshold@v1
        with:
          report-path: ${{ env.inspector_vulnerability_report_path }}
          format: AmazonInspector
          threshold: critical
