name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker-context:
        required: false
        type: string
        default: '.'
      docker-file:
        required: false
        type: string
        default: 'Dockerfile'
      docker-image-name:
        required: false
        type: string
        default: ${{ github.repository }}

permissions:
  contents: read

jobs:
  test-amazon-inspector-image-scan:
    uses: build-failure/starter-workflows/.github/workflows/amazon-inspector-image-scan.yml@main
    with:
      docker-image-name: foo/bar
      docker-context: tests/amazon-inspector-image-scan
      docker-file: Dockerfile
