name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-amazon-inspector-image-scan:
    uses: build-failure/starter-workflows/code-scanning/amazon-inspector-image-scan.yml@main
    with:
      docker-image-name: foo/bar
      docker-context: tests/amazon-inspector-image-scan
      docker-file: Dockerfile
